name = "prikazko-text-generation"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (add these via wrangler secret or dashboard)
# GEMINI_API_KEY = "your-gemini-api-key" (use: wrangler secret put GEMINI_API_KEY)
# ALLOWED_ORIGINS = "https://your-wordpress-site.com,https://www.your-wordpress-site.com"
# API_KEY = "optional-api-key-for-extra-security" (use: wrangler secret put API_KEY)

[vars]
# Non-secret environment variables can go here
# ALLOWED_ORIGINS will be set via wrangler secret or dashboard for security

# Rate limiting (using Cloudflare's built-in rate limiting - FREE!)
# Configured in code: 5 requests per IP per hour


